#! /bin/bash
cd $8

echo "$3 $(cat host.pub)" > KnownHost
if [ $7 = 'get' ]; then
    if [ $6 = 'tor' ]; then
        torify sftp -o StrictHostKeyChecking=yes -o UserKnownHostsFile=KnownHost -i $1 $2@$3:$4 $5
    else
      	sftp -o StrictHostKeyChecking=yes -o UserKnownHostsFile=KnownHost -i $1 $2@$3:$4 $5
    fi
fi

if [ $7 = 'put' ]; then
    if [ $6 = 'tor' ]; then
        torify sftp -o StrictHostKeyChecking=yes -o UserKnownHostsFile=KnownHost -i $1 $2@$3 <<§
put $5 $4
§
    else
	sftp -o StrictHostKeyChecking=yes -o UserKnownHostsFile=KnownHost -i $1 $2@$3 <<§
put $5 $4
§
    fi
fi
