#!/bin/bash

cd /home/$(hostname)/.config/voider/punchit

name_cert=$(ls /home/$(hostname)/.config/voider/servers/servers/$1/cert/)

int_ip=$(cat /home/$(hostname)/.config/voider/self/localip)
ext_ip=$(cat /home/$(hostname)/.config/voider/servers/servers/$1/ext_ip)
ext_port=$(cat /home/$(hostname)/.config/voider/servers/servers/$1/ext_port)
rndsrcport=$(cat /home/$(hostname)/.config/voider/servers/servers/$1/rndsrcport)
to_internet=$(cat /home/$(hostname)/.config/voider/self/int_out)

            
sed -i "4s/.*/ListenPort\ =\ $rndsrcport/" /home/$(hostname)/.config/voider/servers/servers/$1/cert/$name_cert
#put the ip and ports inside the config
sed -i "9s/.*/Endpoint\ =\ $ext_ip:$ext_port/" /home/$(hostname)/.config/voider/servers/servers/$1/cert/$name_cert

echo "changed the config"

iptables -w 2 -t nat -A POSTROUTING -o $to_internet -p udp --sport $rndsrcport -s 172.30.$1.2 -j SNAT --to-source $int_ip:$rndsrcport
ip netns exec netns$1 ip route add "$ext_ip/32" via 172.30.$1.1
iptables -w 2 -t nat -A PREROUTING -i $to_internet -s $ext_ip -j DNAT --to 172.30.$1.2
            
sleep 3s            

conntrack -F

ip netns exec netns$1 wg-quick up /home/$(hostname)/.config/voider/servers/servers/$1/cert/$name_cert

